#!/bin/bash
# ══════════════════════════════════════════════════════════════════════════════
# Saudi Property Finder — One-Command Auto Setup
# Usage: curl -fsSL https://raw.githubusercontent.com/DeveloperSarim/saudi-property-finder/main/setup.sh | bash
# ══════════════════════════════════════════════════════════════════════════════

set -e

# ── Colors ────────────────────────────────────────────────────────────────────
R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'; B='\033[0;34m'; C='\033[0;36m'; NC='\033[0m'; BOLD='\033[1m'

REPO_URL="https://github.com/DeveloperSarim/saudi-property-finder.git"
INSTALL_DIR="/opt/saudi-property-finder"

echo ""
echo -e "${C}${BOLD}╔══════════════════════════════════════════╗${NC}"
echo -e "${C}${BOLD}║   🏠 Saudi Property Finder — Auto Setup  ║${NC}"
echo -e "${C}${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── Step 1: Docker ────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
    echo -e "${Y}[1/6] Installing Docker...${NC}"
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker --now 2>/dev/null || true
    echo -e "${G}✅ Docker installed${NC}"
else
    echo -e "${G}✅ [1/6] Docker already installed ($(docker --version | cut -d' ' -f3 | tr -d ','))${NC}"
fi

# ── Step 2: Docker Compose ────────────────────────────────────────────────────
if ! docker compose version &>/dev/null 2>&1; then
    echo -e "${Y}[2/6] Installing Docker Compose plugin...${NC}"
    apt-get install -y docker-compose-plugin -qq
    echo -e "${G}✅ Docker Compose installed${NC}"
else
    echo -e "${G}✅ [2/6] Docker Compose ready${NC}"
fi

# ── Step 3: Clone or Update repo ──────────────────────────────────────────────
echo -e "${Y}[3/6] Getting latest code from GitHub...${NC}"
if [ -d "$INSTALL_DIR/.git" ]; then
    cd "$INSTALL_DIR"
    git fetch origin main
    git reset --hard origin/main
    echo -e "${G}✅ Code updated to latest${NC}"
else
    git clone "$REPO_URL" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
    echo -e "${G}✅ Repo cloned${NC}"
fi

# ── Step 4: Auto-detect free ports ───────────────────────────────────────────
echo -e "${Y}[4/6] Detecting free ports...${NC}"

find_free_port() {
    local port=$1
    while ss -tlnp 2>/dev/null | grep -q ":${port} " || \
          netstat -tlnp 2>/dev/null | grep -q ":${port} "; do
        port=$((port + 1))
    done
    echo "$port"
}

BACKEND_PORT=$(find_free_port 8001)
FRONTEND_PORT=$(find_free_port 3001)
echo -e "${G}✅ Backend port: ${BOLD}$BACKEND_PORT${NC} ${G}| Frontend port: ${BOLD}$FRONTEND_PORT${NC}"

# ── Step 5: Auto .env ─────────────────────────────────────────────────────────
echo -e "${Y}[5/6] Creating .env configuration...${NC}"

# Get server IP (try multiple methods)
SERVER_IP=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || \
            curl -s --max-time 5 icanhazip.com 2>/dev/null || \
            curl -s --max-time 5 api.ipify.org 2>/dev/null || \
            hostname -I 2>/dev/null | awk '{print $1}' || \
            echo "127.0.0.1")

cat > .env << EOF
# Auto-generated by setup.sh on $(date)
BACKEND_PORT=${BACKEND_PORT}
FRONTEND_PORT=${FRONTEND_PORT}
CORS_ORIGINS=*

# VITE_API_URL is intentionally empty — frontend auto-detects backend
# from window.location.hostname:${BACKEND_PORT} at runtime.
# Set this only if you add a domain + Nginx proxy later:
# VITE_API_URL=https://your-domain.com/api
VITE_API_URL=
EOF

echo -e "${G}✅ .env created${NC}"

# ── Step 6: Build & Launch ────────────────────────────────────────────────────
echo -e "${Y}[6/6] Building and starting containers (this takes 3-5 minutes)...${NC}"
echo ""

docker compose up -d --build 2>&1 | while IFS= read -r line; do
    echo -e "     ${line}"
done

echo ""
echo -e "${G}${BOLD}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${G}${BOLD}║           ✅  Setup Complete!                        ║${NC}"
echo -e "${G}${BOLD}╠══════════════════════════════════════════════════════╣${NC}"
echo -e "${G}${BOLD}║${NC}                                                      ${G}${BOLD}║${NC}"
echo -e "${G}${BOLD}║${NC}  🌐 Frontend:  ${C}http://${SERVER_IP}:${FRONTEND_PORT}${NC}             ${G}${BOLD}║${NC}"
echo -e "${G}${BOLD}║${NC}  🔧 Backend:   ${C}http://${SERVER_IP}:${BACKEND_PORT}${NC}             ${G}${BOLD}║${NC}"
echo -e "${G}${BOLD}║${NC}  💊 Health:    ${C}http://${SERVER_IP}:${BACKEND_PORT}/health${NC}       ${G}${BOLD}║${NC}"
echo -e "${G}${BOLD}║${NC}                                                      ${G}${BOLD}║${NC}"
echo -e "${G}${BOLD}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${Y}Useful commands:${NC}"
echo -e "  ${C}docker compose logs -f backend${NC}   → Backend logs"
echo -e "  ${C}docker compose logs -f frontend${NC}  → Frontend logs"
echo -e "  ${C}docker compose ps${NC}                 → Container status"
echo -e "  ${C}docker compose restart backend${NC}   → Restart backend"
echo ""

# ── Auto-configure Nginx (if installed + sites-available exists) ───────────────
if command -v nginx &>/dev/null && [ -d /etc/nginx/sites-available ]; then
    NGINX_CONF="/etc/nginx/sites-available/saudi-property-finder"
    if [ ! -f "$NGINX_CONF" ]; then
        echo -e "${Y}📡 Nginx detected — adding site config...${NC}"
        cat > "$NGINX_CONF" << NGINXEOF
# Saudi Property Finder — Auto-generated Nginx config
# To enable SSL: certbot --nginx -d your-domain.com

server {
    listen 80;
    server_name ${SERVER_IP};

    # API Backend — SSE streaming enabled
    location /api/ {
        proxy_pass         http://localhost:${BACKEND_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Connection '';
        proxy_buffering    off;
        proxy_cache        off;
        chunked_transfer_encoding on;
        proxy_read_timeout 360s;
        proxy_send_timeout 360s;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-Proto \$scheme;
    }

    location /health {
        proxy_pass http://localhost:${BACKEND_PORT}/health;
    }

    # React Frontend
    location / {
        proxy_pass         http://localhost:${FRONTEND_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
    }
}
NGINXEOF
        ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/saudi-property-finder 2>/dev/null || true
        if nginx -t &>/dev/null; then
            systemctl reload nginx
            echo -e "${G}✅ Nginx configured — app accessible at http://${SERVER_IP}${NC}"
        else
            echo -e "${R}⚠️  Nginx config has errors — check: nginx -t${NC}"
        fi
    else
        echo -e "${G}✅ Nginx site config already exists${NC}"
    fi
fi

echo -e "${B}${BOLD}To update in future, just re-run setup.sh — it will pull latest & rebuild.${NC}"
echo ""
